import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import Providers from "@/components/Providers";
import ToastViewport from "@/app/components/ToastViewport";
import "./globals.css";

interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "نظام إدارة مبيعات الأثاث",
  description: "Generated by SrraJ",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ar" dir="rtl">
      <body id="__next" className="font-Alexandria text-base">
        <AppRouterCacheProvider>
          <Providers>
            <ToastViewport />
            <div>{children}</div>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
